#spring:
#  application:
#    name: qiyu-live-user-provider
#  datasource:
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yaml
#    hikari:
#      pool-name: qiyu-user-pool
#      minimum-idle: 250
#      maximum-pool-size: 400
#      connection-timeout: 100000
#      max-lifetime: 60000
#  data:
#    redis:
#      port: 6379
#      host: 113.44.144.219
#      password: 123456
#      lettuce:
#        pool:
#          min-idle: 10
#          max-active: 100
#          max-idle: 10
#qiyu:
#  rmq:
#    producer:
#      nameSrv: 113.44.144.219:9876
#      groupName: ${spring.application.name}
#      retryTimes: 3
#      sendTimeOut: 10000
#    consumer:
#      nameSrv: 113.44.144.219:9876
#      groupName: ${spring.application.name}
#dubbo:
#  application:
#    name: ${spring.application.name}
#  registry:
#    address: nacos://113.44.144.219:8848?namespace=qiyu-live-test&username=nacos&password=nacos123
#  protocol:
#    name: dubbo
#    port: 9090
#    threadpool: fixed
#    dispatcher: execution
#    threads: 500
#    accepts: 500
#
